on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'foo.pl'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate markdown
        shell: bash
        env:
          PR: ${{ github.event.number }}
        run: |
          perl foo.pl > foo.md
          echo foo.md generated

      - name: Add comment to PR
        if: contains(github.event.comment.body, 'special string')
        env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf '%s\n' "<details>" "<summary>Markdown preview</summary>" "" > msg
          cat foo.md >> msg
          echo '</details>' >> msg
          jq -Rs '{"body":.}' < msg > data.json
          curl -X POST $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "@data.json"
